// flow-typed signature: 4d96788b09374155e6b221d1d2009d22
// flow-typed version: <<STUB>>/react-validator-prop-types_v^1.1.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-validator-prop-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-validator-prop-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-validator-prop-types/lib/ValidatorPropTypes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-validator-prop-types/lib/ValidatorPropTypes.js' {
  declare module.exports: $Exports<'react-validator-prop-types/lib/ValidatorPropTypes'>;
}
